import {
  CONNECTOR_TYPE,
  CONNECTOR_TYPE_COMPANY,
  CONNECTOR_TYPE_USER,
} from "./common";
import type { BasicJobEntity } from "~/entities/user/job";
import type { CompanyEntity } from "~/entities/user/company";
import type { ApplicationEntity } from "~/entities/user/application";

export const HASHTAG_EXAMPLE = [
  { code: "1", name: "Back End" },
  { code: "2", name: "Front End" },
  { code: "3", name: "DevOps" },
  { code: "4", name: "Project Management" },
  { code: "5", name: "Data Analysis" },
  { code: "6", name: "Digital Marketing" },
  { code: "7", name: "Cloud Computing" },
  { code: "8", name: "Python Programming" },
  { code: "9", name: "Sales" },
  { code: "10", name: "Leadership" },
  { code: "11", name: "Communication" },
  { code: "12", name: "SQL" },
  { code: "13", name: "JavaScript" },
  { code: "14", name: "Public Speaking" },
  { code: "15", name: "Adobe Photoshop" },
  { code: "16", name: "Machine Learning" },
  { code: "17", name: "Business Strategy" },
  { code: "18", name: "Customer Service" },
  { code: "19", name: "Social Media Marketing" },
  { code: "20", name: "Problem Solving" },
  { code: "21", name: "UX/UI Design" },
  { code: "22", name: "Agile Methodologies" },
  { code: "23", name: "Financial Analysis" },
  { code: "24", name: "Copywriting" },
  { code: "25", name: "HTML/CSS" },
  { code: "26", name: "Cybersecurity" },
  { code: "27", name: "Google Analytics" },
  { code: "28", name: "Artificial Intelligence" },
  { code: "29", name: "Risk Management" },
  { code: "30", name: "Networking" },
  { code: "31", name: "Software Development" },
  { code: "32", name: "Negotiation" },
  { code: "33", name: "Graphic Design" },
  { code: "34", name: "Strategic Planning" },
  { code: "35", name: "SAP" },
  { code: "36", name: "Product Management" },
  { code: "37", name: "Data Visualization" },
  { code: "38", name: "Accounting" },
  { code: "39", name: "Event Planning" },
  { code: "40", name: "Operations Management" },
  { code: "41", name: "Marketing Strategy" },
  { code: "42", name: "C++ Programming" },
  { code: "43", name: "SEO (Search Engine Optimization)" },
  { code: "44", name: "Tableau" },
  { code: "45", name: "Python Machine Learning" },
  { code: "46", name: "Blockchain" },
  { code: "47", name: "Scrum" },
  { code: "48", name: "Supply Chain Management" },
  { code: "49", name: "Database Management" },
  { code: "50", name: "CRM Software" },
  { code: "51", name: "Customer Relationship Management" },
  { code: "52", name: "AutoCAD" },
  { code: "53", name: "Coaching & Mentoring" },
];

export const DETAIL_COMPANY_SAMPLE: CompanyEntity = {
  id: "1",
  name: "MC Solution",
  name_in_charge: "Hayate Kaneko",
  phone: "0123456678",
  email: "nhphong1804@mcsolution.vn",
  logo: "/images/company_1.jpeg",
  company_type: "IT",
  address: "Da Nang",
  detail_address: "06 Tran Phu, Thach Thang, Hai Chau",
  size: 100,
  accessibility:
    '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3833.6863471442707!2d108.21995387524866!3d16.08175798459955!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3142183c64872e85%3A0x69bf3e739766c927!2zMDYgVHLhuqduIFBow7osIFRo4bqhY2ggVGhhbmcsIEjhuqNpIENow6J1LCDEkMOgIE7hurVuZyA1NTAwMDAsIFZp4buHdCBOYW0!5e0!3m2!1svi!2s!4v1728035487283!5m2!1svi!2s" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>',
  closed_day: "Saturday, Sunday, Holiday",
  business_day: "2-5 weekly",
  connect_company: [1, 2, 3, 4, 5, 6, 7],
  connect_user: [1, 2, 3, 4, 5, 6, 7],
};

export const COMPANY_SAMPLE: CompanyEntity[] = [
  {
    id: "1",
    name: "MC Solution",
    name_in_charge: "Hayate Kaneko",
    phone: "0123456678",
    email: "nhphong1804@mcsolution.vn",
    logo: "/images/company_1.jpeg",
    company_type: "IT",
    address: "Da Nang",
    detail_address: "06 Tran Phu, Thach Thang, Hai Chau",
    size: 100,
    accessibility:
      '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3833.6863471442707!2d108.21995387524866!3d16.08175798459955!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3142183c64872e85%3A0x69bf3e739766c927!2zMDYgVHLhuqduIFBow7osIFRo4bqhY2ggVGhhbmcsIEjhuqNpIENow6J1LCDEkMOgIE7hurVuZyA1NTAwMDAsIFZp4buHdCBOYW0!5e0!3m2!1svi!2s!4v1728035487283!5m2!1svi!2s" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>',
    closed_day: "Saturday, Sunday, Holiday",
    business_day: "2-5 weekly",
  },
  {
    id: "1",
    name: "MC Solution",
    name_in_charge: "Hayate Kaneko",
    phone: "0123456678",
    email: "nhphong1804@mcsolution.vn",
    logo: "/images/company_2.jpeg",
    company_type: "IT",
    address: "Da Nang",
    detail_address: "06 Tran Phu, Thach Thang, Hai Chau",
    size: 100,
    accessibility:
      '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3833.6863471442707!2d108.21995387524866!3d16.08175798459955!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3142183c64872e85%3A0x69bf3e739766c927!2zMDYgVHLhuqduIFBow7osIFRo4bqhY2ggVGhhbmcsIEjhuqNpIENow6J1LCDEkMOgIE7hurVuZyA1NTAwMDAsIFZp4buHdCBOYW0!5e0!3m2!1svi!2s!4v1728035487283!5m2!1svi!2s" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>',
    closed_day: "Saturday, Sunday, Holiday",
    business_day: "2-5 weekly",
  },
  {
    id: "1",
    name: "MC Solution",
    name_in_charge: "Hayate Kaneko",
    phone: "0123456678",
    email: "nhphong1804@mcsolution.vn",
    logo: "/images/company_3.jpeg",
    company_type: "IT",
    address: "Da Nang",
    detail_address: "06 Tran Phu, Thach Thang, Hai Chau",
    size: 100,
    accessibility:
      '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3833.6863471442707!2d108.21995387524866!3d16.08175798459955!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3142183c64872e85%3A0x69bf3e739766c927!2zMDYgVHLhuqduIFBow7osIFRo4bqhY2ggVGhhbmcsIEjhuqNpIENow6J1LCDEkMOgIE7hurVuZyA1NTAwMDAsIFZp4buHdCBOYW0!5e0!3m2!1svi!2s!4v1728035487283!5m2!1svi!2s" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>',
    closed_day: "Saturday, Sunday, Holiday",
    business_day: "2-5 weekly",
  },
  {
    id: "1",
    name: "MC Solution",
    name_in_charge: "Hayate Kaneko",
    phone: "0123456678",
    email: "nhphong1804@mcsolution.vn",
    logo: "/images/company_1.jpeg",
    company_type: "IT",
    address: "Da Nang",
    detail_address: "06 Tran Phu, Thach Thang, Hai Chau",
    size: 100,
    accessibility:
      '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3833.6863471442707!2d108.21995387524866!3d16.08175798459955!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3142183c64872e85%3A0x69bf3e739766c927!2zMDYgVHLhuqduIFBow7osIFRo4bqhY2ggVGhhbmcsIEjhuqNpIENow6J1LCDEkMOgIE7hurVuZyA1NTAwMDAsIFZp4buHdCBOYW0!5e0!3m2!1svi!2s!4v1728035487283!5m2!1svi!2s" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>',
    closed_day: "Saturday, Sunday, Holiday",
    business_day: "2-5 weekly",
  },
  {
    id: "1",
    name: "MC Solution",
    name_in_charge: "Hayate Kaneko",
    phone: "0123456678",
    email: "nhphong1804@mcsolution.vn",
    logo: "/images/company_2.jpeg",
    company_type: "IT",
    address: "Da Nang",
    detail_address: "06 Tran Phu, Thach Thang, Hai Chau",
    size: 100,
    accessibility:
      '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3833.6863471442707!2d108.21995387524866!3d16.08175798459955!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3142183c64872e85%3A0x69bf3e739766c927!2zMDYgVHLhuqduIFBow7osIFRo4bqhY2ggVGhhbmcsIEjhuqNpIENow6J1LCDEkMOgIE7hurVuZyA1NTAwMDAsIFZp4buHdCBOYW0!5e0!3m2!1svi!2s!4v1728035487283!5m2!1svi!2s" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>',
    closed_day: "Saturday, Sunday, Holiday",
    business_day: "2-5 weekly",
  },
];

export const JOB_SAMPLE: BasicJobEntity[] = [
  {
    id: 1,
    title: "Job ngon tháng 10/2024",
    description: "Base on Tokyo",
    salary_from: 1000,
    salary_upto: 1500,
    vacancy: 2,
    position_name: "Backend developer",
    type_of_employee: "Full time",
    address: "Da Nang",
    hashtag: [1, 2, 4],
    interview_type: "Offline",
    company: COMPANY_SAMPLE[0],
  },
  {
    id: 2,
    title: "Job ngon tháng 10/2024",
    description: "Base on Tokyo",
    salary_from: 1000,
    salary_upto: 1500,
    vacancy: 2,
    position_name: "Backend developer",
    type_of_employee: "Part time",
    address: "HCM",
    hashtag: [4, 5, 6],
    interview_type: "Offline",
    company: COMPANY_SAMPLE[1],
  },
  {
    id: 3,
    title: "Job ngon tháng 10/2024",
    description: "Base on Tokyo",
    salary_from: 1000,
    salary_upto: 1500,
    vacancy: 2,
    position_name: "Front developer",
    type_of_employee: "Full time",
    address: "Da Nang",
    hashtag: [1, 3, 7],
    interview_type: "Offline",
    company: COMPANY_SAMPLE[2],
  },
  {
    id: 4,
    title: "Job ngon tháng 10/2024",
    description: "Base on Tokyo",
    salary_from: 1000,
    salary_upto: 1500,
    vacancy: 2,
    position_name: "Backend developer",
    type_of_employee: "Full time",
    address: "Da Nang",
    hashtag: [2],
    interview_type: "Offline",
    company: COMPANY_SAMPLE[3],
  },
];

export const USER_EXAMPLE = {
  id: "1",
  last_name: "phong",
  first_name: "nguyen hoang",
  date_of_birth: "2002/18/04",
  avatar: "/images/avatar_2.jpg",
  email: "nhphong1804@gmail.com",
  address: "Da Nang",
  detail_address: "Lien Chieu, Chon Tam 4, 76",
  is_married: false,
  gender: "male",
  self_introduce: "I'm currently student in Da Nang University of technology",
  life_goal: "Become a solution architecture",
  job_title: "Backend developer",
  hashtag: [1, 2, 3, 6, 8, 9],
  // hashtag: [],
  connect_company: [1, 2, 4, 9, 11, 3],
  connect_user: [1, 2, 4, 9, 11, 3],
};

export const CONNECTOR_SAMPLE = [
  {
    id: "1",
    first_name: "Phong",
    last_name: "Nguyen Hoang",
    avatar: "/images/avatar_2.jpg",
    connector_type: CONNECTOR_TYPE[CONNECTOR_TYPE_COMPANY],
    // connector_position: mappingHashtag(1).name,
  },
  {
    id: "2",
    first_name: "Anh",
    last_name: "Nguyen Cong",
    connector_type: CONNECTOR_TYPE[CONNECTOR_TYPE_COMPANY],
    avatar: "/images/avatar_3.jpeg",
    // connector_position: mappingHashtag(1).name,
  },
  {
    id: "3",
    first_name: "Quan",
    last_name: "Than Nguyen Minh",
    avatar: "/images/avatar_4.jpeg",
    connector_type: CONNECTOR_TYPE[CONNECTOR_TYPE_COMPANY],
    // connector_position: mappingHashtag(2).name,
  },
  {
    id: "4",
    first_name: "Truong",
    last_name: "Pham Van Tien",
    connector_type: CONNECTOR_TYPE[CONNECTOR_TYPE_USER],
    avatar: "/images/avatar_5.jpeg",
    // connector_position: mappingHashtag(3).name,
  },
  {
    id: "5",
    first_name: "Bach",
    last_name: "Le Trong",
    connector_type: CONNECTOR_TYPE[CONNECTOR_TYPE_USER],
    avatar: "/images/avatar_6.jpeg",
    // connector_position: mappingHashtag(4).name,
  },
  {
    id: "6",
    first_name: "Vy",
    last_name: "Pham Luu Tuong",
    connector_type: CONNECTOR_TYPE[CONNECTOR_TYPE_USER],
    avatar: "/images/avatar_2.jpg",
    // connector_position: mappingHashtag(5).name,
  },
  {
    id: "7",
    first_name: "Truong",
    last_name: "Vo Huu Nam",
    connector_type: CONNECTOR_TYPE[CONNECTOR_TYPE_USER],
    avatar: "/images/avatar_3.jpeg",
    // connector_position: mappingHashtag(6).name,
  },
  {
    id: "8",
    first_name: "Vinh",
    last_name: "Trinh Quang",
    connector_type: CONNECTOR_TYPE[CONNECTOR_TYPE_USER],
    avatar: "/images/avatar_4.jpeg",
    // connector_position: mappingHashtag(7).name,
  },
  {
    id: "9",
    first_name: "Vu",
    last_name: "Nguyen Hoang",
    connector_type: CONNECTOR_TYPE[CONNECTOR_TYPE_USER],
    avatar: "/images/avatar_5.jpeg",
    // connector_position: mappingHashtag(8).name,
  },
  {
    id: "10",
    first_name: "Duc",
    last_name: "Nguyen Dac",
    connector_type: CONNECTOR_TYPE[CONNECTOR_TYPE_USER],
    avatar: "/images/avatar_6.jpeg",
    // connector_position: mappingHashtag(10).name,
  },
  {
    id: "11",
    first_name: "Hai",
    last_name: "Tran Van",
    connector_type: CONNECTOR_TYPE[CONNECTOR_TYPE_USER],
    avatar: "/images/avatar_2.jpg",
    // connector_position: mappingHashtag(11).name,
  },
  {
    id: "12",
    first_name: "Huy",
    last_name: "Pham Cong",
    connector_type: CONNECTOR_TYPE[CONNECTOR_TYPE_USER],
    avatar: "/images/avatar_3.jpeg",
    // connector_position: mappingHashtag(12).name,
  },
  {
    id: "13",
    first_name: "Vy",
    last_name: "Nguyen Thi Quynh",
    connector_type: CONNECTOR_TYPE[CONNECTOR_TYPE_USER],
    avatar: "/images/avatar_4.jpeg",
    // connector_position: mappingHashtag(13).name,
  },
  {
    id: "14",
    first_name: "Nghi",
    last_name: "Nguyen Tue",
    connector_type: CONNECTOR_TYPE[CONNECTOR_TYPE_USER],
    avatar: "/images/avatar_5.jpeg",
    // connector_position: mappingHashtag(14).name,
  },
  {
    id: "15",
    first_name: "Khoi",
    last_name: "Nguyen Minh",
    connector_type: CONNECTOR_TYPE[CONNECTOR_TYPE_USER],
    avatar: "/images/avatar_6.jpeg",
    // connector_position: mappingHashtag(15).name,
  },
  {
    id: "16",
    first_name: "Luffy",
    last_name: "Monkey D.",
    connector_type: CONNECTOR_TYPE[CONNECTOR_TYPE_USER],
    avatar: "/images/avatar_2.jpg",
    // connector_position: mappingHashtag(16).name,
  },
];

export const APPLICATION_SAMPLE: ApplicationEntity[] = [
  {
    id: "1",
    job_id: "2",
    job_name: "Backend developer",
    first_name: "Nguyen Hoang",
    last_name: "Phong",
    date_of_birth: "2002/04/18",
    avatar: "/images/avatar_2.jpg",
    email: "nhphong1804@gmail.com",
    phone: "0912345678",
    address: "Da Nang",
    detail_address: "Lien Chieu, Hoa Khanh Nam",
    is_married: false,
    gender: "Male",
    self_introduce: "",
    life_goal: "None",
    job_title: "Senior backend developer",
    interview_status: 2,
    interview_type: 1,
    note: "",
    interview_date_time: "2024/10/1 9:00",
    onboard_date: "",
    company: COMPANY_SAMPLE[0],
    job: JOB_SAMPLE[0],
  },
  {
    id: "2",
    job_id: "2",
    job_name: "Frontend developer",
    first_name: "Nguyen Hoang",
    last_name: "Phong",
    date_of_birth: "2002/04/18",
    avatar: "/images/avatar_2.jpg",
    email: "nhphong1804@gmail.com",
    phone: "0912345678",
    address: "Da Nang",
    detail_address: "Lien Chieu, Hoa Khanh Nam",
    is_married: false,
    gender: "Male",
    self_introduce: "",
    life_goal: "None",
    job_title: "Senior frontend developer",
    interview_status: 2,
    interview_type: 2,
    note: "",
    interview_date_time: "",
    onboard_date: "",
    company: COMPANY_SAMPLE[1],
    job: JOB_SAMPLE[1],
  },
];
